#!/bin/sh

set -eu

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

readonly REPO_NAME="mac-config"
readonly REPO_URL="https://github.com/pervezfunctor/${REPO_NAME}.git"
readonly DOT_DIR="$HOME/.${REPO_NAME}"

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BOLD='\033[1m'
RESET='\033[0m'

log() { printf "${GREEN}✔${RESET} %s\n\n" "$*"; }
warn() { printf "${YELLOW}${BOLD}⚠${RESET} %s\n\n" "$*" >&2; }
die() {
  printf "${RED}${BOLD}✖${RESET} %s\n\n" "$*" >&2
  exit 1
}

dotfiles_install() {
  has_cmd git || die "git not found. Quitting."

  if [ ! -d "$DOT_DIR" ]; then
    log "Cloning dotfiles to $DOT_DIR."
    git clone "$REPO_URL" "$DOT_DIR" || die "Failed to clone $REPO_URL"
  elif [ -z "$(git -C "$DOT_DIR" status --porcelain)" ]; then
    log "Dotfiles repo clean. Pulling latest changes..."
    if ! git -C "$DOT_DIR" pull --rebase; then
      log "Rebase failed. Aborting."
      git -C "$DOT_DIR" rebase --abort || die "Failed to abort rebase."
    fi
  else
    log "Dotfiles repo dirty. Skipping update"
  fi
}

system_install() {
  if ! xcode-select -p >/dev/null 2>&1; then
    log "Installing Xcode Command Line Tools. Re-run the script after installation finishes."
    xcode-select --install
    exit 0
  else
    log "Xcode Command Line Tools already installed. Skipping."
  fi

  # if [ "$(uname -m)" = "arm64" ] && ! pkgutil --pkg-info com.apple.pkg.RosettaUpdateAuto >/dev/null 2>&1; then
  #   log "Installing Rosetta Update. It's okay if this fails."
  #   /usr/sbin/softwareupdate --install-rosetta --agree-to-license || true
  # else
  #   log "Rosetta Update already installed. Skipping."
  # fi
}

brew_install() {
  if has_cmd brew; then
    log "Updating brew..."
    brew update
    brew upgrade -y
    return
  fi

  log "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  log "Homebrew installed."
}

brew_packages_install() {
  log "Installing homebrew packages..."
  brew install -y -q nushell font-jetbrains-mono-nerd-font uv
  log "Homebrew packages installed."
}

zsh_setup() {
  touch ~/.zshrc
  if ! grep -q "source ${DOT_DIR}/zsh/zshrc" ~/.zshrc; then
    log "Sourcing ${DOT_DIR}/zsh/zshrc in ${HOME}/.zshrc"
    echo "source ${DOT_DIR}/zsh/zshrc" >>~/.zshrc
  fi
}

main() {
  export PATH="$HOME/.local/bin:${DOT_DIR}/scripts:/opt/homebrew/bin:/usr/local/bin:$PATH"

  [ "$(uname)" = "Darwin" ] || die "Not a Mac. Quitting."

  echo ""
  log "Starting mac setup..."
  echo ""

  system_install
  dotfiles_install
  brew_install
  brew_packages_install
  zsh_setup

  echo ""
  log "mac setup complete! Use 'setup.nu' interactive script for further setup."
  echo ""
}

main "$@"
